# Live model
model: fofr/any-comfyui-workflow

# A private model to run the test against before pushing
test_model: fofr/any-comfyui-workflow-staging
test_hardware: gpu-l40s

# Tests
predict:
  compare_outputs: false
  predict_timeout: 600
  test_cases:
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/sd15_txt2img.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/flux_pulid_with_attn_mask_api.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/advanced_live_portrait_api.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/brushnet_powerpaint_api.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/comfyui_essentials_all_workflows.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/glif_custom_lora_flux_hf.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/instantid_default_api.json
        return_temp_files: true
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/ipadapter_faceid.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/kolors_and_ipadapter_api.json
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/reactor_api.json
