# Live model
model: fofr/sandbox

# A private model to run the test against before pushing
test_model: fofr/any-comfyui-workflow-staging
test_hardware: gpu-l40s

# Tests
predict:
  compare_outputs: false
  predict_timeout: 300
  test_cases:
    - inputs:
        workflow_json: https://raw.githubusercontent.com/fofr/cog-comfyui/refs/heads/main/examples/api_workflows/sd15_txt2img.json
